# This is an autogenerated nbx_user.py file for a [NBX](www.nimblebox.ai) app:
# created time: Tuesday W28 [ UTC 12 Jul, 2022 - 15:43:11 ]
#   created by: yash_6352

import os

os.environ["NBOX_LOG_LEVEL"] = "DEBUG" # Keep it the way you like

from nbox import Operator
from nbox.hyperloop.job_pb2 import Resource
from nbox.jobs import Schedule
from nbox import logger # Use this logger when needed

from src import MLOps, ServingPipeline

def get_op(serving: bool = False) -> Operator:
  logger.info(f"Creating Operator ---> serving={serving}")
  if not serving:
    return MLOps(
      file = __file__,
      deployment_id = "<>", # "auto" will create a new deployment based on the job name
      workspace_id = "<>",      # "auto" will create a new workspace based on the job name
    )
  return ServingPipeline()

def get_resource() -> Resource:
  """Define your pod config here"""
  return Resource(
    cpu = "50m",         # 100mCPU
    memory = "100Mi",     # MiB
    disk_size = "1Gi",    # GiB
    gpu = "none",         # keep "none" for no GPU
    gpu_count = "0",      # keep "0" when no GPU
    timeout = 120_000,    # 2 minutes between attempts
    max_retries = 3,      # third times the charm :P
  )

def get_schedule() -> Schedule:
  # only relevant for NBX-Jobs
  # define your schedule here, if None will run only once.
  return None